# -*- coding: utf-8 -*-
"""
代码生成模板
"""
from pymp.generator.introspect import TableInfo

MODEL_TEMPLATE = """# -*- coding: utf-8 -*-
# Auto-generated by pymp generator
from datetime import datetime
from typing import Optional
from pymp.model import BaseModel, TableName, TableId


@TableName("{table_name}")
class {class_name}(BaseModel):
    \"\"\"{table_comment}\"\"\"
{fields_code}
"""

MAPPER_TEMPLATE = """# -*- coding: utf-8 -*-
# Auto-generated by pymp generator
from pymp.mapper import BaseMapper
from pymp.annotation import select, insert, update, delete


class {class_name}Mapper(BaseMapper):
    table_name = "{table_name}"
    primary_key = "{pk_name}"

    def get_connection(self):
        from flask import current_app
        return current_app.instance_db.get_connection()
"""


def render_model_code(info: TableInfo) -> str:
    """生成 Model 代码"""
    fields_lines = []
    for col in info.columns:
        pk_mark = ' = TableId()' if col.is_pk else ''
        comment_mark = f'  # {col.comment}' if col.comment else ''
        fields_lines.append(f"    {col.name}: Optional[{col.py_type}]{pk_mark}{comment_mark}")

    fields_code = "\n".join(fields_lines)
    return MODEL_TEMPLATE.format(
        table_name=info.table_name,
        class_name=info.class_name,
        table_comment=info.comment,
        fields_code=fields_code
    )


def render_mapper_code(info: TableInfo) -> str:
    """生成 Mapper 代码"""
    pk_name = "id"
    for col in info.columns:
        if col.is_pk:
            pk_name = col.name
            break

    return MAPPER_TEMPLATE.format(
        table_name=info.table_name,
        class_name=info.class_name,
        pk_name=pk_name
    )